# Generated by Django 3.2 on 2021-09-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='Primeiro Nome')),
                ('last_name', models.CharField(max_length=128, verbose_name='Sobrenome')),
                ('date_of_birth', models.DateField(verbose_name='Data de nascimento')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128, verbose_name='Senha')),
                ('nickname', models.CharField(max_length=16, verbose_name='Apelido')),
                ('is_active', models.BooleanField(default=False, verbose_name='Usuario Ativo?')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Funcionário?')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Admnistrador?')),
                ('last_login', models.DateTimeField(null=True, verbose_name='Ultimo login')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima atualização')),
                ('groups', models.ManyToManyField(blank=True, help_text='Grupo ao qual o usuário pertence. O usuário recebe todas as permissões dos grupos ao qual ele pertence.', related_name='user_groups', related_query_name='user', to='auth.Group', verbose_name='Grupos de usuário')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Permissões específicas do usuário.', related_name='user_permissions', related_query_name='user', to='auth.Permission', verbose_name='Permissões do usuário')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
    ]
